backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "index-page"

          - label: Title
            name: title
            widget: string

          - label: Image
            name: image
            widget: image

          - label: Heading
            name: heading
            widget: string

          - label: Subheading
            name: subheading
            widget: string

          - label: Sections
            name: sections
            widget: list
            allow_add: true
            fields:
              -
                label: Heading
                name: heading
                widget: string
                default: "Heading"
              -
                label: Content
                name: content
                widget: text
                default: "Content..."
              -
                label: Style
                name: style
                widget: select
                options: ["style1", "style2", "style3"]
                default: "style1"

          - label: Address
            name: address
            widget: object
            fields: 
              - label: "Line 1"
                name: line1
                widget: string
              - label: "Line 2"
                name: line2
                widget: string
              - label: City
                name: city
                widget: string
              - label: "Postal Code"
                name: postalCode
                widget: string
              - label: Country
                name: country
                widget: string


      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}